apiVersion: apps/v1
kind: Deployment
metadata:
  name: kk-payments

spec:
  replicas: 2

  selector:
    matchLabels:
      app: kk-payments

  template:
    metadata:
      labels:
        app: kk-payments

    spec:
      imagePullSecrets:
        - name: kijani-registry-credentials

      containers:
        - name: kk-payments

          image: YOUR_REGISTRY/kk-payments:YOUR_TAG

          imagePullPolicy: Always

          ports:
            - containerPort: 3001

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"

            limits:
              cpu: "500m"
              memory: "512Mi"