---
# SSH

ansible_user: ubuntu
ansible_python_interpreter: /usr/bin/python3

# Application Directories

app_base_dir: /opt/kijanikiosk
app_config_dir: /opt/kijanikiosk/config
app_log_dir: /var/log/kijanikiosk

# Service Accounts

api_user: kk-api
payments_user: kk-payments
logs_user: kk-logs

# Environment Variables

api_port: 8080
payments_port: 8081
logs_port: 8082

api_environment: staging
payments_environment: staging
logs_environment: staging

# Application Commands

api_start_command: "/usr/bin/python3 -m http.server {{ api_port }}"
payments_start_command: "/usr/bin/python3 -m http.server {{ payments_port }}"
logs_start_command: "/usr/bin/python3 -m http.server {{ logs_port }}"

# Logrotate

logrotate_rotate: 7
logrotate_frequency: daily
logrotate_compress: true

# Systemd Hardening

payments_no_new_privileges: true
payments_private_tmp: true
payments_protect_system: strict
payments_protect_home: true
payments_protect_kernel_tunables: true
payments_protect_kernel_modules: true
payments_protect_control_groups: true
payments_memory_deny_write_execute: true
payments_restrict_realtime: true
payments_lock_personality: true

# Firewall

allowed_tcp_ports:
  - 22
  - 80
  - 443

# Common Tags

project_name: KijaniKiosk
environment: staging